### ISSUE TITLE
摩斯密码的接口好像坏掉了？

### ISSUE THREAD

**Issue by PrussianBlueCN** [hanhan258/hanhan-plugin#3]
尝试使用失败，报错：
FetchError: request to https://xiaobapi.top/api/xb/api/mesdm.php?type=en&msg=2333 failed, reason: connect ECONNREFUSED 198.44.165.242:443
0|Yunzai-B |     at ClientRequest.<anonymous> (file:///root/Yunzai-Bot/node_modules/.pnpm/node-fetch@3.3.1/node_modules/node-fetch/src/index.js:108:11)
0|Yunzai-B |     at ClientRequest.emit (node:events:513:28)
0|Yunzai-B |     at TLSSocket.socketErrorListener (node:_http_client:490:9)
0|Yunzai-B |     at TLSSocket.emit (node:events:513:28)
0|Yunzai-B |     at emitErrorNT (node:internal/streams/destroy:151:8)
0|Yunzai-B |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
0|Yunzai-B |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by hanhan258** [comment]
等我晚上修吧
