### ISSUE TITLE
搜一搜一直是30000ms erorr

### ISSUE THREAD

**Issue by wzq10314** [hanhan258/hanhan-plugin#40]
不管是外网还是百度之类全都是秒30000ms erorr，但是我网络正常，其他插件也能正常截图网页

**Comment by hanhan258** [comment]
windows还是linux

**Comment by wzq10314** [comment]
> windows还是linux

debian12

**Comment by hanhan258** [comment]
> > windows还是linux
> 
> debian12

插件更新到最新版，然后安装一下google chrome,并把路径配置到config.json试试

**Comment by wzq10314** [comment]
> > > windows还是linux
> > 
> > 
> > debian12
> 
> 插件更新到最新版，然后安装一下google chrome,并把路径配置到config.json试试

我没图形界面用的chromium，然后config里只有pingtoken这行

**Comment by hanhan258** [comment]
> > > > windows还是linux
> > > 
> > > 
> > > debian12
> > 
> > 插件更新到最新版，然后安装一下google chrome,并把路径配置到config.json试试
> 
> 我没图形界面用的chromium，然后config里只有pingtoken这行

百度一下chrome安装方法，把config.example.json的chromF那一行复制过去，路径改成你自己的，或者用锅巴配置也行

**Comment by wzq10314** [comment]
> 

好的 我去试试谢谢

**Comment by wzq10314** [comment]
> 
装好了chrome（114.0.5735.198-1），路径也填了 😭没有效果，还是30000ms，那个无头模式我也从锅巴里把他关了

**Comment by hanhan258** [comment]
> > 
> 装好了chrome（114.0.5735.198-1），路径也填了 😭没有效果，还是30000ms，那个无头模式我也从锅巴里把他关了

没有图形化界面，要把无头模式打开的，配置完记得重启

**Comment by wzq10314** [comment]
> > > 
> > 
> > 
> > 装好了chrome（114.0.5735.198-1），路径也填了 😭没有效果，还是30000ms，那个无头模式我也从锅巴里把他关了
> 
> 没有图形化界面，要把无头模式打开的，配置完记得重启
![image](https://github.com/hanhan258/hanhan-plugin/assets/21983217/1ada6d87-0d36-4cbd-8f89-cbc0aa2a6372)
开启无头模式我也试过（每次配置都重启）。
路径我填的是/opt/google/chrome/chrome
还是寄

**Comment by hanhan258** [comment]
> > > > 
> > > 
> > > 
> > > 装好了chrome（114.0.5735.198-1），路径也填了 😭没有效果，还是30000ms，那个无头模式我也从锅巴里把他关了
> > 
> > 没有图形化界面，要把无头模式打开的，配置完记得重启
> ![image](https://github.com/hanhan258/hanhan-plugin/assets/21983217/1ada6d87-0d36-4cbd-8f89-cbc0aa2a6372)
> 开启无头模式我也试过（每次配置都重启）。
> 路径我填的是/opt/google/chrome/chrome
> 还是寄
> 

执行一下which google-chrome命令，看看跟配置的一样不

**Comment by wzq10314** [comment]
> 

emmm不一样，/usr/bin/google-chrome，我改了现在，但还是超时，无头开启
![image](https://github.com/hanhan258/hanhan-plugin/assets/21983217/90dddefa-3268-41be-95bb-f1fe579c94d5)

**Comment by wzq10314** [comment]
然后/usr/bin/google-chrome里是个快捷方式，指向的就是/opt/google/chrome/这个路径，我服务器也是国内的

**Comment by hanhan258** [comment]
> 然后/usr/bin/google-chrome里是个快捷方式，指向的就是/opt/google/chrome/这个路径，我服务器也是国内的

我似乎知道什么原因了稍等一下

**Comment by wzq10314** [comment]
> > 然后/usr/bin/google-chrome里是个快捷方式，指向的就是/opt/google/chrome/这个路径，我服务器也是国内的
> 
> 我似乎知道什么原因了稍等一下
嗯嗯好的！辛苦了

**Comment by hanhan258** [comment]
推送了，更新一下试试

**Comment by wzq10314** [comment]
> 推送了，更新一下试试

推送后正常了！感谢！
