### ISSUE TITLE
发送视频消息失败

### ISSUE THREAD

**Issue by hurylove** [hanhan258/hanhan-plugin#41]
![image](https://github.com/hanhan258/hanhan-plugin/assets/111729799/70231afb-f165-403f-ad1d-7faee67bce4a)
提示我[MiaoYz][00:20:24.704][ERRO] ApiRejection { code: -60, message: 'ffmpeg获取视频
图像帧失败' }
可我在bot.yaml中已经配置了路径了，版本是5.1.2
![image](https://github.com/hanhan258/hanhan-plugin/assets/111729799/70231afb-f165-403f-ad1d-7faee67bce4a)

不知道具体的原因了

**Comment by hanhan258** [comment]
配置一下环境变量试试

**Comment by hurylove** [comment]
> 

![image](https://github.com/hanhan258/hanhan-plugin/assets/111729799/b3c140a7-7a8a-40db-9bdd-a69d6b3c8f26)
配置好了，还是这个问题
![image](https://github.com/hanhan258/hanhan-plugin/assets/111729799/298f2fa1-5220-4985-a164-efc23f79633e)

**Comment by azianuo** [comment]
[解决了吗？
![QQ截图20230801104823](https://github.com/hanhan258/hanhan-plugin/assets/131458083/6ac87659-b4cf-420f-869b-19136d33a721)

**Comment by azianuo** [comment]
> [解决了吗？ ![QQ截图20230801104823](https://user-images.githubusercontent.com/131458083/257392416-6ac87659-b4cf-420f-869b-19136d33a721.png)

我的也这样

**Comment by hanhan258** [comment]
> > [解决了吗？ ![QQ截图20230801104823](https://user-images.githubusercontent.com/131458083/257392416-6ac87659-b4cf-420f-869b-19136d33a721.png)
> 
> 我的也这样

换个版本试试？

**Comment by azianuo** [comment]
> > > [解决了吗？ ![QQ截图20230801104823](https://user-images.githubusercontent.com/131458083/257392416-6ac87659-b4cf-420f-869b-19136d33a721.png)
> > 
> > 
> > 我的也这样
> 
> 换个版本试试？

啊？什么换版本

**Comment by hanhan258** [comment]
> > > > [解决了吗？ ![QQ截图20230801104823](https://user-images.githubusercontent.com/131458083/257392416-6ac87659-b4cf-420f-869b-19136d33a721.png)
> > > 
> > > 
> > > 我的也这样
> > 
> > 换个版本试试？
> 
> 啊？什么换版本

ffmpeg的版本，试试这个里面的版本https://www.123pan.com/s/qsWcVv-KmF43.html

**Comment by hanhan258** [comment]
> > > > [解决了吗？ ![QQ截图20230801104823](https://user-images.githubusercontent.com/131458083/257392416-6ac87659-b4cf-420f-869b-19136d33a721.png)
> > > 
> > > 
> > > 我的也这样
> > 
> > 换个版本试试？
> 
> 啊？什么换版本

是windows吧

**Comment by azianuo** [comment]
> > > > > [解决了吗？ ![QQ截图20230801104823](https://user-images.githubusercontent.com/131458083/257392416-6ac87659-b4cf-420f-869b-19136d33a721.png)
> > > > 
> > > > 
> > > > 我的也这样
> > > 
> > > 
> > > 换个版本试试？
> > 
> > 
> > 啊？什么换版本
> 
> 是windows吧

谢谢，不过太麻烦了就不弄了就这样吧

**Comment by hurylove** [comment]
我是更换了ff的版本修好的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月1日(星期二) 晚上7:18
收件人: "hanhan258/hanhan-plugin";
抄送: "Author";
主题: Re: [hanhan258/hanhan-plugin] 发送视频消息失败 (Issue #41)





      
[解决了吗？ 
  
我的也这样
  
换个版本试试？
  
啊？什么换版本
  
是windows吧
  
谢谢，不过太麻烦了就不弄了就这样吧
 
&mdash;

**Comment by devil233-ui** [comment]
> > > > > [解决了吗？ ![QQ截图20230801104823](https://user-images.githubusercontent.com/131458083/257392416-6ac87659-b4cf-420f-869b-19136d33a721.png)
> > > > 
> > > > 
> > > > 我的也这样
> > > 
> > > 
> > > 换个版本试试？
> > 
> > 
> > 啊？什么换版本
> 
> ffmpeg的版本，试试这个里面的版本https://www.123pan.com/s/qsWcVv-KmF43.html

我换了并不能解决问题……
![image](https://github.com/user-attachments/assets/32746cd8-18ab-4552-899c-4cea6568806e)
![image](https://github.com/user-attachments/assets/eb490750-a134-49d3-98a9-0d71786dc6cd)
![image](https://github.com/user-attachments/assets/10c41826-7082-4424-a69e-007b70814095)

**Comment by hurylove** [comment]
> > > > > > [解决了吗？![QQ截图20230801104823](https://user-images.githubusercontent.com/131458083/257392416-6ac87659-b4cf-420f-869b-19136d33a721.png)
> > > > > 
> > > > > 
> > > > > 我的也这样
> > > > 
> > > > 
> > > > 换个版本试试？
> > > 
> > > 
> > > 啊？什么换版本
> > 
> > 
> > ffmpeg的版本，试试这个里面的版本 https://www.123pan.com/s/qsWcVv-KmF43.html
> 
> 我换了并不能解决问题…… ![图像](https://private-user-images.githubusercontent.com/69190444/350086208-32746cd8-18ab-4552-899c-4cea6568806e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTA3MjcsIm5iZiI6MTcyMTM1MDQyNywicGF0aCI6Ii82OTE5MDQ0NC8zNTAwODYyMDgtMzI3NDZjZDgtMThhYi00NTUyLTg5OWMtNGNlYTY1Njg4MDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAwNTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwODkzMWUxY2U0OTM4YmM1NzRkZDA3ZjQxMTlhMjJlZmYwNmI2MDk1ZTQyZGZkMzA3OTQ4ZjVkNmEwMzBjOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T8XTJJ0DYcdyTT4dVE91awlvOvSRe9Q5eGyVpITY1Lk) ![图像](https://private-user-images.githubusercontent.com/69190444/350091598-eb490750-a134-49d3-98a9-0d71786dc6cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTA3MjcsIm5iZiI6MTcyMTM1MDQyNywicGF0aCI6Ii82OTE5MDQ0NC8zNTAwOTE1OTgtZWI0OTA3NTAtYTEzNC00OWQzLTk4YTktMGQ3MTc4NmRjNmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAwNTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YmQ1Y2Q3NjIzYzg0YmY1NTQ3M2UxNGMyZGExOGQ4Y2IwN2E5ZGRhMDA2ZmVlMTk2YjdlNDI1MTRmMjBmZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rwISp8nGaCutOcxQ-5WUYlKOGRI580kd7hAa_O4Lhmw) ![图像](https://private-user-images.githubusercontent.com/69190444/350092066-10c41826-7082-4424-a69e-007b70814095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTA3MjcsIm5iZiI6MTcyMTM1MDQyNywicGF0aCI6Ii82OTE5MDQ0NC8zNTAwOTIwNjYtMTBjNDE4MjYtNzA4Mi00NDI0LWE2OWUtMDA3YjcwODE0MDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAwNTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMDY3NzUwMmJhOGJjNWQzNDc2Y2IxYzFiZmMzMzQ5ZjUzNjBiMDZhMGQ3MjhmODFmMDI5OWJmODI1NGJjMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r5bh4iQDbGdiisp7HydW8IiY1_ASL7wUesG4o-z0FOE)

设置了环境变量，就不需要额外配置了

**Comment by devil233-ui** [comment]
> 设置了环境变量，就不需要额外配置了

这个倒不是重点吧（
我最开始确实是看你配了锅巴才补上的，但现在把锅巴设置去了也没影响
