### ISSUE TITLE
搜一搜没有反应

### ISSUE THREAD

**Issue by CICILC** [hanhan258/hanhan-plugin#43]
其他功能正常使用 搜一搜不会触发
![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/81b89c3b-7f56-4763-be8a-dcb98a54be21)
google-chrome已经配置了
![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/1ed4ad67-c0f5-4f8b-b3a3-67c8e945b9a6)
![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/83a1b96f-0fdb-469c-a674-e49e7168ba88)

**Comment by hanhan258** [comment]
> 其他功能正常使用 搜一搜不会触发
> ![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/81b89c3b-7f56-4763-be8a-dcb98a54be21)
> google-chrome已经配置了
> ![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/1ed4ad67-c0f5-4f8b-b3a3-67c8e945b9a6)
> ![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/83a1b96f-0fdb-469c-a674-e49e7168ba88)
> 

插件似乎没有加载成功，重启看看是不是有报错

**Comment by CICILC** [comment]
![Screenshot_20230811_023317_Termux](https://github.com/hanhan258/hanhan-plugin/assets/115946224/750a24ed-322e-418a-92ae-1f56ba29b423)
插件加载是没问题的
功能上除了这个js别的都能正常用 这个里面有一部分能用（比如百度等）有一部分不能用（比如cpu等）
![Screenshot_20230811_023015_Termux](https://github.com/hanhan258/hanhan-plugin/assets/115946224/5aef1115-ca03-4b0d-97a5-5d90cf6b7ab1)
（百度的虽然报错但是能用 可能是版本问题 但cpu的直接不能触发）

**Comment by hanhan258** [comment]
> 
> ![Screenshot_20230811_023317_Termux](https://github.com/hanhan258/hanhan-plugin/assets/115946224/750a24ed-322e-418a-92ae-1f56ba29b423)
> 插件加载是没问题的
> 功能上除了这个js别的都能正常用 这个里面有一部分能用（比如百度等）有一部分不能用（比如cpu等）
> ![Screenshot_20230811_023015_Termux](https://github.com/hanhan258/hanhan-plugin/assets/115946224/5aef1115-ca03-4b0d-97a5-5d90cf6b7ab1)
> （百度的虽然报错但是能用 可能是版本问题 但cpu的直接不能触发）

百度这个不是报错，是正常现象，cpu这个看着像指令被抢了

**Comment by CICILC** [comment]
我感觉还是google-chrome的问题 后来我才发现 这个生效的百度也是其他插件触发的（碎月）憨憨插件除了搜一搜都能正常使用 搜一搜就毫无反应 应该还是这个“依赖”chrome的问题
![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/cc017afe-84fe-477a-a7d5-5b09c512dcd4)

**Comment by CICILC** [comment]
等我再研究研究再提issue吧 谢谢大佬了 或者大佬能不能考虑不使用google-chrome 因为Ubuntu不知道是不是和win方式一样（小建议）感谢大佬
