### ISSUE TITLE
搜一搜没有反应

### ISSUE THREAD

**Issue by CICILC** [hanhan258/hanhan-plugin#45]
重新表述一下情况
![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/d2e9e6cd-a3b3-4475-878e-7283c77dee47)
插件加载没问题 依赖也安装了 chrome也配置了
![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/79f3bbc8-069c-4543-92c3-976549847654)
![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/8c99142f-e889-4465-9bd8-116b4cdb3399)
使用其他功能都正常
![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/0451b956-c002-4521-a4eb-712d2dd8c361)

但是搜一搜就一点反应都没 之前受其他插件影响 我把其他插件先处理了 现在就算搜一搜里面的都没有触发
![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/20a934b0-77c8-4339-81f2-493e407c05b9)
但在系统指令表合集里面能看到已经识别到了
![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/eeb2a2ee-6bce-4117-8f54-93590e7a35d8)
现在我有点怀疑shi是不是我系统问题了 感谢大佬

**Comment by hanhan258** [comment]
> 重新表述一下情况
> ![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/d2e9e6cd-a3b3-4475-878e-7283c77dee47)
> 插件加载没问题 依赖也安装了 chrome也配置了
> ![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/79f3bbc8-069c-4543-92c3-976549847654)
> ![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/8c99142f-e889-4465-9bd8-116b4cdb3399)
> 使用其他功能都正常
> ![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/0451b956-c002-4521-a4eb-712d2dd8c361)
> 
> 但是搜一搜就一点反应都没 之前受其他插件影响 我把其他插件先处理了 现在就算搜一搜里面的都没有触发
> ![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/20a934b0-77c8-4339-81f2-493e407c05b9)
> 但在系统指令表合集里面能看到已经识别到了
> ![image](https://github.com/hanhan258/hanhan-plugin/assets/115946224/eeb2a2ee-6bce-4117-8f54-93590e7a35d8)
> 现在我有点怀疑shi是不是我系统问题了 感谢大佬

方便让我进服务器调试吗
