### ISSUE TITLE
弱智吧功能无法返回消息

### ISSUE THREAD

**Issue by Harunoluna** [hanhan258/hanhan-plugin#46]
安装环境为安卓手机Termux，使用Xshell链接。
后台收发反馈具体情况如下：（主人qq号已替换）

[YzBot][02:54:26.980][INFO] recv from: [Private: 000000000(friend)] 弱智吧
[YzBot][02:54:27.028][MARK] [憨憨图片类][rzb][私聊][XX000000000] 弱智吧
{
  name: '我爱的人💤',
  time: '2023-08-12 21:28:52',
  title: '朱元璋都当上皇帝了，为什么他小时候要去要饭？',
  text: '小时候不是小皇帝吗？',
  images: []
}
[YzBot][02:54:27.783][MARK] [憨憨图片类][rzb] 弱智吧 处理完成 750ms
[YzBot][02:54:30.429][ERRO] failed to send: [Group: NaN] undefined(1)
[YzBot][02:54:30.431][ERRO] ApiRejection { code: 1, message: 'unknown' }

最后两行为红色报错

请问是因为该功能只能在群内使用导致的问题吗？能否通过修改部分代码解决

**Comment by hanhan258** [comment]
> 安装环境为安卓手机Termux，使用Xshell链接。 后台收发反馈具体情况如下：（主人qq号已替换）
> 
> [YzBot][02:54:26.980][INFO] recv from: [Private: 000000000(friend)] 弱智吧 [YzBot][02:54:27.028][MARK] [憨憨图片类][rzb][私聊][XX000000000] 弱智吧 { name: '我爱的人💤', time: '2023-08-12 21:28:52', title: '朱元璋都当上皇帝了，为什么他小时候要去要饭？', text: '小时候不是小皇帝吗？', images: [] } [YzBot][02:54:27.783][MARK] [憨憨图片类][rzb] 弱智吧 处理完成 750ms [YzBot][02:54:30.429][ERRO] failed to send: [Group: NaN] undefined(1) [YzBot][02:54:30.431][ERRO] ApiRejection { code: 1, message: 'unknown' }
> 
> 最后两行为红色报错
> 
> 请问是因为该功能只能在群内使用导致的问题吗？能否通过修改部分代码解决

更新一下，或许需要手动重启，然后再私聊弱智吧试试

**Comment by Harunoluna** [comment]
> > 安装环境为安卓手机Termux，使用Xshell链接。 后台收发反馈具体情况如下：（主人qq号已替换）
> > [YzBot][02:54:26.980][INFO] recv from: [Private: 000000000(friend)] 弱智吧 [YzBot][02:54:27.028][MARK] [憨憨图片类][rzb][私聊][XX000000000] 弱智吧 { name: '我爱的人💤', time: '2023-08-12 21:28:52', title: '朱元璋都当上皇帝了，为什么他小时候要去要饭？', text: '小时候不是小皇帝吗？', images: [] } [YzBot][02:54:27.783][MARK] [憨憨图片类][rzb] 弱智吧 处理完成 750ms [YzBot][02:54:30.429][ERRO] failed to send: [Group: NaN] undefined(1) [YzBot][02:54:30.431][ERRO] ApiRejection { code: 1, message: 'unknown' }
> > 最后两行为红色报错
> > 请问是因为该功能只能在群内使用导致的问题吗？能否通过修改部分代码解决
> 
> 更新一下，或许需要手动重启，然后再私聊弱智吧试试

更新+重启，问题未解决
简单测试了一下，具体情况为：
- 群内使用弱智吧功能时，尝试很多次，text和images值总是为空（无法获取到内容？），name,time,title这三条有值，所以回复了这三条消息，回复方式为qq的合并转发
- 私聊使用时，可以正常获取到全部内容，但是会报错，具体报错和上面一样

具体截图如下（选择你的拍屏导师）
![_1490127108__cad78d831fe72fec248d6f1adbfe4088_-724475390_20230813_180505_0_wifi_0](https://github.com/hanhan258/hanhan-plugin/assets/63052675/8539d990-077a-449c-9da0-0829e5647d8d)

**Comment by hanhan258** [comment]
> > > 安装环境为安卓手机Termux，使用Xshell链接。 后台收发反馈具体情况如下：（主人qq号已替换）
> > > [YzBot][02:54:26.980][INFO] recv from: [Private: 000000000(friend)] 弱智吧 [YzBot][02:54:27.028][MARK] [憨憨图片类][rzb][私聊][XX000000000] 弱智吧 { name: '我爱的人💤', time: '2023-08-12 21:28:52', title: '朱元璋都当上皇帝了，为什么他小时候要去要饭？', text: '小时候不是小皇帝吗？', images: [] } [YzBot][02:54:27.783][MARK] [憨憨图片类][rzb] 弱智吧 处理完成 750ms [YzBot][02:54:30.429][ERRO] failed to send: [Group: NaN] undefined(1) [YzBot][02:54:30.431][ERRO] ApiRejection { code: 1, message: 'unknown' }
> > > 最后两行为红色报错
> > > 请问是因为该功能只能在群内使用导致的问题吗？能否通过修改部分代码解决
> > 
> > 更新一下，或许需要手动重启，然后再私聊弱智吧试试
> 
> 更新+重启，问题未解决
> 简单测试了一下，具体情况为：
> - 群内使用弱智吧功能时，尝试很多次，text和images值总是为空（无法获取到内容？），name,time,title这三条有值，所以回复了这三条消息，回复方式为qq的合并转发
> - 私聊使用时，可以正常获取到全部内容，但是会报错，具体报错和上面一样
> 
> 具体截图如下（选择你的拍屏导师）
> ![_1490127108__cad78d831fe72fec248d6f1adbfe4088_-724475390_20230813_180505_0_wifi_0](https://github.com/hanhan258/hanhan-plugin/assets/63052675/8539d990-077a-449c-9da0-0829e5647d8d)
> 

为空是正常的，有的有内容，有的没有，有图片发送失败我需要再看看

**Comment by hanhan258** [comment]
> > > 安装环境为安卓手机Termux，使用Xshell链接。 后台收发反馈具体情况如下：（主人qq号已替换）
> > > [YzBot][02:54:26.980][INFO] recv from: [Private: 000000000(friend)] 弱智吧 [YzBot][02:54:27.028][MARK] [憨憨图片类][rzb][私聊][XX000000000] 弱智吧 { name: '我爱的人💤', time: '2023-08-12 21:28:52', title: '朱元璋都当上皇帝了，为什么他小时候要去要饭？', text: '小时候不是小皇帝吗？', images: [] } [YzBot][02:54:27.783][MARK] [憨憨图片类][rzb] 弱智吧 处理完成 750ms [YzBot][02:54:30.429][ERRO] failed to send: [Group: NaN] undefined(1) [YzBot][02:54:30.431][ERRO] ApiRejection { code: 1, message: 'unknown' }
> > > 最后两行为红色报错
> > > 请问是因为该功能只能在群内使用导致的问题吗？能否通过修改部分代码解决
> > 
> > 更新一下，或许需要手动重启，然后再私聊弱智吧试试
> 
> 更新+重启，问题未解决
> 简单测试了一下，具体情况为：
> - 群内使用弱智吧功能时，尝试很多次，text和images值总是为空（无法获取到内容？），name,time,title这三条有值，所以回复了这三条消息，回复方式为qq的合并转发
> - 私聊使用时，可以正常获取到全部内容，但是会报错，具体报错和上面一样
> 
> 具体截图如下（选择你的拍屏导师）
> ![_1490127108__cad78d831fe72fec248d6f1adbfe4088_-724475390_20230813_180505_0_wifi_0](https://github.com/hanhan258/hanhan-plugin/assets/63052675/8539d990-077a-449c-9da0-0829e5647d8d)
> 

我刚测试了一下，我这面是正常的，你用的是哪个版本的崽（喵喵的还是trss）,icqq是哪个版本呢

**Comment by Harunoluna** [comment]
找个这个教程来的https://gitee.com/CUZNIL/Yunzai-install，应该是trss
icqq是最新版本，好像是.13

**Comment by Harunoluna** [comment]
> > > > 安装环境为安卓手机Termux，使用Xshell链接。 后台收发反馈具体情况如下：（主人qq号已替换）
> > > > [YzBot][02:54:26.980][INFO] recv from: [Private: 000000000(friend)] 弱智吧 [YzBot][02:54:27.028][MARK] [憨憨图片类][rzb][私聊][XX000000000] 弱智吧 { name: '我爱的人💤', time: '2023-08-12 21:28:52', title: '朱元璋都当上皇帝了，为什么他小时候要去要饭？', text: '小时候不是小皇帝吗？', images: [] } [YzBot][02:54:27.783][MARK] [憨憨图片类][rzb] 弱智吧 处理完成 750ms [YzBot][02:54:30.429][ERRO] failed to send: [Group: NaN] undefined(1) [YzBot][02:54:30.431][ERRO] ApiRejection { code: 1, message: 'unknown' }
> > > > 最后两行为红色报错
> > > > 请问是因为该功能只能在群内使用导致的问题吗？能否通过修改部分代码解决
> > > 
> > > 
> > > 更新一下，或许需要手动重启，然后再私聊弱智吧试试
> > 
> > 
> > 更新+重启，问题未解决
> > 简单测试了一下，具体情况为：
> > 
> > * 群内使用弱智吧功能时，尝试很多次，text和images值总是为空（无法获取到内容？），name,time,title这三条有值，所以回复了这三条消息，回复方式为qq的合并转发
> > * 私聊使用时，可以正常获取到全部内容，但是会报错，具体报错和上面一样
> > 
> > 具体截图如下（选择你的拍屏导师）
> > ![1490127108__cad78d831fe72fec248d6f1adbfe4088-724475390_20230813_180505_0_wifi_0](https://user-images.githubusercontent.com/63052675/260296301-8539d990-077a-449c-9da0-0829e5647d8d.png)
> 
> 为空是正常的，有的有内容，有的没有，有图片发送失败我需要再看看

又测试了十几条，群聊功能是正常使用的，图片也能发送，但是私聊功能无论有没有text，或者image，始终就是报错，无任何回复

**Comment by hanhan258** [comment]
> > > > > 安装环境为安卓手机Termux，使用Xshell链接。 后台收发反馈具体情况如下：（主人qq号已替换）
> > > > > [YzBot][02:54:26.980][INFO] recv from: [Private: 000000000(friend)] 弱智吧 [YzBot][02:54:27.028][MARK] [憨憨图片类][rzb][私聊][XX000000000] 弱智吧 { name: '我爱的人💤', time: '2023-08-12 21:28:52', title: '朱元璋都当上皇帝了，为什么他小时候要去要饭？', text: '小时候不是小皇帝吗？', images: [] } [YzBot][02:54:27.783][MARK] [憨憨图片类][rzb] 弱智吧 处理完成 750ms [YzBot][02:54:30.429][ERRO] failed to send: [Group: NaN] undefined(1) [YzBot][02:54:30.431][ERRO] ApiRejection { code: 1, message: 'unknown' }
> > > > > 最后两行为红色报错
> > > > > 请问是因为该功能只能在群内使用导致的问题吗？能否通过修改部分代码解决
> > > > 
> > > > 
> > > > 更新一下，或许需要手动重启，然后再私聊弱智吧试试
> > > 
> > > 
> > > 更新+重启，问题未解决
> > > 简单测试了一下，具体情况为：
> > > 
> > > * 群内使用弱智吧功能时，尝试很多次，text和images值总是为空（无法获取到内容？），name,time,title这三条有值，所以回复了这三条消息，回复方式为qq的合并转发
> > > * 私聊使用时，可以正常获取到全部内容，但是会报错，具体报错和上面一样
> > > 
> > > 具体截图如下（选择你的拍屏导师）
> > > ![1490127108__cad78d831fe72fec248d6f1adbfe4088-724475390_20230813_180505_0_wifi_0](https://user-images.githubusercontent.com/63052675/260296301-8539d990-077a-449c-9da0-0829e5647d8d.png)
> > 
> > 为空是正常的，有的有内容，有的没有，有图片发送失败我需要再看看
> 
> 又测试了十几条，群聊功能是正常使用的，图片也能发送，但是私聊功能无论有没有text，或者image，始终就是报错，无任何回复

那就不太清楚了，我这私聊群聊都正常

**Comment by Harunoluna** [comment]
> > > > > > 安装环境为安卓手机Termux，使用Xshell链接。 后台收发反馈具体情况如下：（主人qq号已替换）
> > > > > > [YzBot][02:54:26.980][INFO] recv from: [Private: 000000000(friend)] 弱智吧 [YzBot][02:54:27.028][MARK] [憨憨图片类][rzb][私聊][XX000000000] 弱智吧 { name: '我爱的人💤', time: '2023-08-12 21:28:52', title: '朱元璋都当上皇帝了，为什么他小时候要去要饭？', text: '小时候不是小皇帝吗？', images: [] } [YzBot][02:54:27.783][MARK] [憨憨图片类][rzb] 弱智吧 处理完成 750ms [YzBot][02:54:30.429][ERRO] failed to send: [Group: NaN] undefined(1) [YzBot][02:54:30.431][ERRO] ApiRejection { code: 1, message: 'unknown' }
> > > > > > 最后两行为红色报错
> > > > > > 请问是因为该功能只能在群内使用导致的问题吗？能否通过修改部分代码解决
> > > > > 
> > > > > 
> > > > > 更新一下，或许需要手动重启，然后再私聊弱智吧试试
> > > > 
> > > > 
> > > > 更新+重启，问题未解决
> > > > 简单测试了一下，具体情况为：
> > > > 
> > > > * 群内使用弱智吧功能时，尝试很多次，text和images值总是为空（无法获取到内容？），name,time,title这三条有值，所以回复了这三条消息，回复方式为qq的合并转发
> > > > * 私聊使用时，可以正常获取到全部内容，但是会报错，具体报错和上面一样
> > > > 
> > > > 具体截图如下（选择你的拍屏导师）
> > > > ![1490127108__cad78d831fe72fec248d6f1adbfe4088-724475390_20230813_180505_0_wifi_0](https://user-images.githubusercontent.com/63052675/260296301-8539d990-077a-449c-9da0-0829e5647d8d.png)
> > > 
> > > 
> > > 为空是正常的，有的有内容，有的没有，有图片发送失败我需要再看看
> > 
> > 
> > 又测试了十几条，群聊功能是正常使用的，图片也能发送，但是私聊功能无论有没有text，或者image，始终就是报错，无任何回复
> 
> 那就不太清楚了，我这私聊群聊都正常

好吧，感谢回复:)
