### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by Fhm-newbie** [hanhan258/hanhan-plugin#73]
![图片](https://github.com/hanhan258/hanhan-plugin/assets/63446200/a4d0ed2b-b1a1-4a59-b969-556369196368)

**Comment by Fhm-newbie** [comment]
某天开始未知原因憨憨帮助指令会出现如图报错，
![图片](https://github.com/hanhan258/hanhan-plugin/assets/63446200/e2b7e108-c9ba-41c7-9b31-60620c47c114)
且使用视频功能虽然能正常使用但后续也会发出类似报错

**Comment by hanhan258** [comment]
更新
